"""Stage-1 `score_inview` adapter construction, shared by every caller.

Three notebooks need the same two scorers over the same corpus:
`evaluation_harness.ipynb` (A1 Q4, the "before" numbers),
`reranker_scores.ipynb` (A2 Q2, the re-ranker's training features), and
`reranker_evaluation.ipynb` (A2 Q2, the "after" numbers). They were
originally written twice, which is a live correctness risk rather than
just duplication: `bm25_score`/`embedding_score` are *features* the
booster was fitted on, so any drift between the notebook that produced
the training values and the one that produces them at serving time
shifts the input distribution under a fixed model, silently. Having one
implementation makes that class of bug impossible rather than merely
unlikely.

The memory shape here is the version arrived at in A2 Q2 (SPEC.md A2 Q2
#3): history truncated in Arrow, embeddings converted columnar. The
older per-notebook copies built the same objects the naive way and cost
roughly 12GB more on this machine.

The two copies were not quite identical, and the difference is worth
recording. `evaluation_harness.ipynb` built its embedding lookup with
`np.asarray(v)` over Python floats, so the *query* vector was pooled in
float64 before being compared against a float32 corpus;
`reranker_scores.ipynb` pools in float32 throughout. Measured over 3,000
`ebnerd` val impressions the scores differ by at most 1.192e-07 (float32
epsilon), with zero ranking-order flips and per-impression AUC equal to
ten decimal places -- so A1's already-published baselines stand. This
module follows the float32 path, because that is the one the booster's
training features were actually generated by, and matching the model's
input distribution matters more than matching the older harness.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import polars as pl

from .bm25 import build_index, get_scores, tokenize
from .embeddings import cosine_similarity_subset, mean_pool, normalize_rows

# Number of most-recent history clicks that define a user's query. Fixed
# here rather than per-notebook for the same reason the scorers are: it
# is baked into the re-ranker's training features.
RECENT_N_CLICKS = 20


def build_stage1_scorers(
    articles: pl.DataFrame,
    history_path: Path,
    embeddings_path: Path,
    recent_n: int = RECENT_N_CLICKS,
) -> dict:
    """`{"bm25": fn, "embedding": fn, ...}` where each `fn(user_id,
    article_ids)` returns `{article_id: score}` over exactly the ids given.

    `articles` must carry `article_id`/`title`/`abstract`; extra columns are
    ignored. Paths are read here rather than taken as frames so the caller
    never holds the untruncated history or the raw embedding frame.
    """
    texts = (articles["title"].fill_null("") + " " + articles["abstract"].fill_null("")).to_list()
    index = build_index(articles["article_id"].to_list(), [tokenize(t) for t in texts])
    title_lookup = dict(zip(articles["article_id"].to_list(), articles["title"].to_list()))
    bm25_id_to_idx = {aid: i for i, aid in enumerate(index.doc_ids)}

    # .list.to_array(dim).to_numpy(), not [np.asarray(v) for v in .to_list()]:
    # the list comprehension materializes ~96M Python floats to build a 385MB
    # matrix, which measured a 4.80GB peak (and was 39x slower). Converting
    # in Arrow lands straight in a numpy block. emb_lookup then holds VIEWS
    # into that block rather than 125,541 separate arrays.
    emb = pl.read_parquet(embeddings_path)
    dim = len(emb["embedding"][0])
    emb_mat = emb["embedding"].list.to_array(dim).to_numpy().astype(np.float32)
    emb_pos = {aid: i for i, aid in enumerate(emb["article_id"].to_list())}
    doc_ids = articles["article_id"].to_numpy()
    missing = [aid for aid in doc_ids if aid not in emb_pos]
    if missing:
        raise ValueError(f"{len(missing)} articles have no embedding (first: {missing[:3]})")
    matrix = emb_mat[np.array([emb_pos[aid] for aid in doc_ids])]
    emb_lookup = {aid: matrix[i] for i, aid in enumerate(doc_ids)}
    corpus_unit = normalize_rows(matrix)
    emb_id_to_idx = {aid: i for i, aid in enumerate(doc_ids)}
    del emb, emb_mat, emb_pos

    # History truncated to the last `recent_n` clicks in Arrow before any
    # Python conversion: both scorers only read that window, so this is
    # exactly equivalent, but the full sequences cost 8.61GB at
    # ebnerd_large's 131,918,897 elements against 1.27GB truncated
    # (SPEC.md A2 Q2 #3).
    history_lookup = dict(zip(*(
        pl.scan_parquet(history_path)
        .select("user_id", pl.col("article_id_sequence").list.tail(recent_n))
        .collect()
        .to_dict(as_series=False)
        .values()
    )))

    # One-entry cache, not an LRU: callers iterate impressions sorted by
    # user_id, so consecutive impressions from the same user hit it and a
    # larger cache would only add retained BM25 score arrays (one float64
    # per corpus doc each) for no additional hit rate.
    cache = {"user_id": None, "scores": None}

    def bm25_fn(user_id, article_ids, impression_id=None):
        if cache["user_id"] != user_id:
            seq = list(history_lookup.get(user_id, []))[-recent_n:]
            tokens = tokenize(" ".join(t for t in (title_lookup.get(a, "") for a in seq) if t))
            cache["user_id"], cache["scores"] = user_id, get_scores(index, tokens)
        scores = cache["scores"]
        return {aid: float(scores[bm25_id_to_idx[aid]]) for aid in article_ids}

    def embedding_fn(user_id, article_ids, impression_id=None):
        seq = list(history_lookup.get(user_id, []))[-recent_n:]
        query = mean_pool(seq, emb_lookup)
        scored = cosine_similarity_subset(query, corpus_unit, doc_ids, emb_id_to_idx, article_ids)
        return {aid: scored.get(aid, 0.0) for aid in article_ids}

    # Top-200 membership is NOT built here: see reranker.topk_membership_pairs.
    # It is attached once, columnar, after scoring.
    return {
        "bm25": bm25_fn,
        "embedding": embedding_fn,
        "n_docs": index.n_docs,
        "users": history_lookup.keys(),
    }
